[package]
name = "canastra-client"
description = "The Canastra game client."
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
canastra-data.workspace = true
canastra-net.workspace = true
canastra-protocol.workspace = true
canastra-ui.workspace = true
glyphon.workspace = true
l2-catalog.workspace = true
l2-crypto.workspace = true
l2-env.workspace = true
pollster.workspace = true
ue2-assets.workspace = true
ue2-level.workspace = true
tokio = { workspace = true, features = ["rt", "net", "sync", "time"] }
ue2-package.workspace = true
wgpu.workspace = true
winit.workspace = true

[lints]
workspace = true
